routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DataFeedController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PersonaController;
use App\Http\Controllers\ProfesionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'login');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::resource('persona',PersonaController::class);
    Route::resource('profesion',ProfesionController::class);

    // Route for the getting the data feed
    Route::get('/json-data-feed', [DataFeedController::class, 'getDataFeed'])->name('json_data_feed');

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::fallback(function() {
        return view('pages/utility/404');
    });    
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/profesiones/create.blade.php
<x-app-layout>
<div class="toast">
        <div class="toast-content">
            <i class="fas fa-solid fa-check check"></i>

            <div class="message">
                <span class="text text-1">Exito</span>
                <span class="text text-2">Datos registrados correctamente</span>
            </div>
            </div>
            <i class="fa-solid fa-xmark close"></i>

            <div class="progress"></div>
        </div>
    <!-- <form action="{{route('profesion.store')}}" method="POST">
        @csrf
        <div>
            <label for="nombre">Nombre profesion</label>
            <input type="text" name="nombre">
        </div>

        <input type="submit" value="Registrar">
    </form> -->
    <div class="login-box">
        <h2>Registro Profesiones</h2>
        <form action="{{route('profesion.store')}}" method="POST">
            @csrf
            <div class="user-box">
                <input type="text" name="nombre" required="">
                <label for="nombre">Nombre Profesion</label>
            </div>
            
            <a href="#" onclick="document.forms[0].submit();">
                <span></span>
                <span></span>
                <span></span>
                <span></span><input id="button" type="submit" value="Registrar">
            </a>
        </form>
    </div>

</x-app-layout>


<script>
var button = document.getElementById("button"),
      toast = document.querySelector(".toast")
      closeIcon = document.querySelector(".close"),
      progress = document.querySelector(".progress");

      let timer1, timer2;

      button.addEventListener("click", () => {
        toast.classList.add("active");
        progress.classList.add("active");

        timer1 = setTimeout(() => {
            toast.classList.remove("active");
        }, 5000); //1s = 1000 milliseconds

        timer2 = setTimeout(() => {
          progress.classList.remove("active");
        }, 5300);
      });
      
      closeIcon.addEventListener("click", () => {
        toast.classList.remove("active");
        
        setTimeout(() => {
          progress.classList.remove("active");
        }, 300);

        clearTimeout(timer1);
        clearTimeout(timer2);
      });

</script>

resources/views/profesiones/edit.blade.php
<x-app-layout>
        <div class="toast">
            <div class="toast-content">
                <i class="fas fa-solid fa-check check"></i>

                <div class="message">
                    <span class="text text-1">Exito</span>
                    <span class="text text-2">Datos actualizados correctamente</span>
                </div>
                </div>
                <i class="fa-solid fa-xmark close"></i>

            <div class="progress"></div>
        </div>

    <div class="login-box">
        <h2>Registro Profesiones</h2>
        <form action="{{route('profesion.update',$profesion->id)}}" method="POST">
            @csrf
            @method('PUT')
            <div class="user-box">
                <input type="text" name="nombre" required="" value={{$profesion->nombre}}>
                <label for="nombre">Nombre Profesion</label>
            </div>
            
            <a href="#" onclick="document.forms[0].submit();">
                
                <span></span><input id="button" type="submit" value="Actualizar">
            </a>
        </form>
    </div>
</x-app-layout>


<script>
var button = document.getElementById("button"),
      toast = document.querySelector(".toast")
      closeIcon = document.querySelector(".close"),
      progress = document.querySelector(".progress");

      let timer1, timer2;

      button.addEventListener("click", () => {
        toast.classList.add("active");
        progress.classList.add("active");

        timer1 = setTimeout(() => {
            toast.classList.remove("active");
        }, 5000); //1s = 1000 milliseconds

        timer2 = setTimeout(() => {
          progress.classList.remove("active");
        }, 5300);
      });
      
      closeIcon.addEventListener("click", () => {
        toast.classList.remove("active");
        
        setTimeout(() => {
          progress.classList.remove("active");
        }, 300);

        clearTimeout(timer1);
        clearTimeout(timer2);
      });

</script>

resources/views/profesiones/index.blade.php
<x-app-layout>
    <div class="col-span-full xl:col-span-8 bg-white shadow-lg rounded-sm border border-slate-200">
        <header class="px-5 py-4 border-b border-slate-100">
            <h2 class="font-semibold text-slate-800">Profesiones</h2>
            <a href="{{route('profesion.create')}}">Añadir Profesion</a>
        </header>
        <div class="p-3">
            

            <!-- Table -->
            <div class="overflow-x-auto">
                <table class="table-auto w-full">
                    <!-- Table header -->
                    <thead class="text-xs uppercase text-slate-400 bg-slate-50 rounded-sm">
                        <tr>
                            <th class="p-2">
                                <div class="font-semibold text-center">Nombre profesion</div>
                            </th>
                            <th class="p-2">
                                <div class="font-semibold text-center">Operaciones</div>
                            </th>
                        </tr>

                    </thead>
                    <!-- Table body -->
                    <tbody class="text-sm font-medium divide-y divide-slate-100">
                        @foreach ($profesiones as $profesion)
                        <tr>
                            <td class="p-2">
                                <div class="flex items-center">
                                    <svg class="shrink-0 mr-2 sm:mr-3" width="36" height="36" viewBox="0 0 36 36">
                                        <circle fill="#24292E" cx="18" cy="18" r="18"></circle>
                                        <path
                                            d="M18 10.2c-4.4 0-8 3.6-8 8 0 3.5 2.3 6.5 5.5 7.6.4.1.5-.2.5-.4V24c-2.2.5-2.7-1-2.7-1-.4-.9-.9-1.2-.9-1.2-.7-.5.1-.5.1-.5.8.1 1.2.8 1.2.8.7 1.3 1.9.9 2.3.7.1-.5.3-.9.5-1.1-1.8-.2-3.6-.9-3.6-4 0-.9.3-1.6.8-2.1-.1-.2-.4-1 .1-2.1 0 0 .7-.2 2.2.8.6-.2 1.3-.3 2-.3s1.4.1 2 .3c1.5-1 2.2-.8 2.2-.8.4 1.1.2 1.9.1 2.1.5.6.8 1.3.8 2.1 0 3.1-1.9 3.7-3.7 3.9.3.4.6.9.6 1.6v2.2c0 .2.1.5.6.4 3.2-1.1 5.5-4.1 5.5-7.6-.1-4.4-3.7-8-8.1-8z"
                                            fill="#FFF"></path>
                                    </svg>
                                    <div class="text-slate-800">{{$profesion->nombre}}</div>
                                </div>
                            </td>
                            <td>
                                <a href="{{route('profesion.edit',$profesion->id)}}">Editar</a>
                                <a > / </a>
                                <a href="{{route('profesion.destroy',$profesion->id)}}">Eliminar</a>
                            </td> 
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>




        


</x-app-layout>

resources/views/profesiones/show.blade.php
<x-app-layout>
    <li>
        Nombre:
        {{$profesion->nombre}}
    </li>
<a href="{{route('profesion.index')}}">Listar</a>
</x-app-layout>